-- MySQL Script generated by MySQL Workbench
-- Wed Oct 28 07:19:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blastech_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blastech_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blastech_db` DEFAULT CHARACTER SET utf8 ;
USE `blastech_db` ;

-- -----------------------------------------------------
-- Table `blastech_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blastech_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `adress` VARCHAR(100) NULL,
  `city` VARCHAR(100) NULL,
  `province` VARCHAR(45) NULL,
  `date` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blastech_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blastech_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blastech_db`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blastech_db`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blastech_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blastech_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `discount` INT NOT NULL,
  `images` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `features` VARCHAR(500) NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `id_category_idx` (`category_id` ASC),
  INDEX `id_brand_idx` (`brand_id` ASC),
  CONSTRAINT `id_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `blastech_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_brand`
    FOREIGN KEY (`brand_id`)
    REFERENCES `blastech_db`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blastech_db`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blastech_db`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `payment` VARCHAR(45) NOT NULL,
  `bill` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `id_product_idx` (`product_id` ASC),
  INDEX `id_user_idx` (`user_id` ASC),
  CONSTRAINT `id_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `blastech_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `blastech_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
